language: python
cache: pip
python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
    - if [[ $TRAVIS_PYTHON_VERSION == *"3."* ]]; then sudo apt-get install python3-numpy python3-scipy; fi
install:
    - pip install -U pip wheel
    - pip install numpy
    - pip install scipy nose pytest sphinx numpydoc sphinx-rtd-theme
    - pip install -e .
script:
    - py.test
    - python setup.py build_sphinx
    - python setup.py egg_info -b.dev sdist --formats gztar
