language: python
cache: pip
python:
    - 3.4
    - 3.5
    - 3.6
    - 3.7
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
    - pip install -U pip wheel
    - pip install -r requirements-dev.txt
    - pip install -e .
script:
    - python -m pytest --doctest-modules sktensor
    - python setup.py build_sphinx
    - python setup.py egg_info -b.dev sdist --formats gztar
